version: "3.8"

name: my-yugabytedb

services:

  yugabytedb-master:
    image: yugabytedb/yugabyte:2.16.3.0-b43
    container_name: yugabytedb-master
    volumes:
      - ${YUGABYTE_VOLUME_DIR}:/home/yugabyte/yb_data
    command: [ "/home/yugabyte/bin/yugabyted",
               "start",
               "--base_dir=/home/yugabyte/yb_data",
               "--daemon=false"
    ]
    ports:
      - "7000:7000"
      - "9000:9000"
      - "9042:9042"
      - "5433:5433"
    networks:
      - yugabytedb-network

networks:
  yugabytedb-network:
